version: '3.7'

services:
 jenkins:
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JENKINS_OPTS="--httpPort=8080"

volumes:
 jenkins_home:
